[package]
name = "true-and-false"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
default-run = "true"

[[bin]]
name = "true"
path = "true.rs"

[[bin]]
name = "false"
path = "false.rs"
