[package]
name = "posix-true"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[[bin]]
name = "true"
path = "main.rs"

[profile.dev]
panic = "abort"

[profile.release]
strip = true  # Strip symbols from binary.
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"

[dependencies]
libc = { version = "*", default-features = false }
